#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
runcmd: 
  - |
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
    apt-get install -y nodejs
